# Generated by Django 3.2.5 on 2022-11-23 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('item_description', models.TextField(validators=[django.core.validators.MaxLengthValidator(100, 'Describe the item in 100 characters')])),
                ('item_image', models.ImageField(upload_to='item_images')),
            ],
        ),
    ]
