# Generated by Django 3.2.5 on 2023-01-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
