# Generated by Django 3.2.5 on 2023-01-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230126_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
