# Generated by Django 3.2.5 on 2023-01-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shipping_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
